# Generated by Django 6.0.3 on 2026-03-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='business_license',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
