export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const SELLER_APPLY_REQUEST = 'SELLER_APPLY_REQUEST';
export const SELLER_APPLY_SUCCESS = 'SELLER_APPLY_SUCCESS';
export const SELLER_APPROVE_REQUEST = 'SELLER_APPROVE_REQUEST';
export const SELLER_APPROVE_SUCCESS = 'SELLER_APPROVE_SUCCESS';