export const SUB_LIST_REQUEST = 'SUB_LIST_REQUEST';
export const SUB_LIST_SUCCESS = 'SUB_LIST_SUCCESS';

export const SUB_DETAILS_REQUEST = 'SUB_DETAILS_REQUEST';
export const SUB_DETAILS_SUCCESS = 'SUB_DETAILS_SUCCESS';
export const SUB_DETAILS_FAIL = 'SUB_DETAILS_FAIL';

export const AI_USAGE_REQUEST = 'AI_USAGE_REQUEST';
export const AI_USAGE_SUCCESS = 'AI_USAGE_SUCCESS';
export const AI_USAGE_DECREMENT = 'AI_USAGE_DECREMENT';

export const USE_AI_QUESTION = 'USE_AI_QUESTION';