export const SUB_TIERS_REQUEST = 'SUB_TIERS_REQUEST';
export const SUB_TIERS_SUCCESS = 'SUB_TIERS_SUCCESS';
export const SUB_TIERS_FAIL = 'SUB_TIERS_FAIL';

export const SUB_DETAILS_REQUEST = 'SUB_DETAILS_REQUEST';
export const SUB_DETAILS_SUCCESS = 'SUB_DETAILS_SUCCESS';
export const SUB_DETAILS_FAIL = 'SUB_DETAILS_FAIL';

export const SUBSCRIBE_REQUEST = 'SUBSCRIBE_REQUEST';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const SUBSCRIBE_FAIL = 'SUBSCRIBE_FAIL';

export const USE_AI_QUESTION = 'USE_AI_QUESTION';

export const SUBSCRIPTION_LIST_ALL_REQUEST = 'SUBSCRIPTION_LIST_ALL_REQUEST';
export const SUBSCRIPTION_LIST_ALL_SUCCESS = 'SUBSCRIPTION_LIST_ALL_SUCCESS';
export const SUBSCRIPTION_LIST_ALL_FAIL = 'SUBSCRIPTION_LIST_ALL_FAIL';